# Generated by Django 6.0.2 on 2026-04-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(help_text='Google Drive ID or Local File Path', max_length=1024, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('source', models.CharField(choices=[('cloud', 'Google Drive'), ('local', 'Local File')], max_length=20)),
                ('is_selected', models.BooleanField(default=True, help_text='True if the user wants this file indexed')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Error'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hash to detect local file changes', max_length=128, null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Last modified time from OS or Cloud', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
